# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0014_auto_20160928_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='real_total_points',
            field=models.FloatField(blank=True, default=0.0, verbose_name='real total points'),
        ),
    ]
