# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-23 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0015_userstory_real_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='real_total_points',
            field=models.FloatField(blank=True, default=0.0, verbose_name='real_total_points'),
        ),
    ]
